name: CI

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: set up cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: go-${{runner.os}}-${{ hashFiles('go.mod')}}
        restore-keys: |
          go-${{runner.os}}-


    - name: "Set up go lang"
      uses: actions/setup-go@v3
      with:
        go-version: "1.22"

    - name: Install dependencies
      run: go mod download

    - name: build applciation
      run: go build -v .
    